Repository pokt-foundation/grove-portal, pull requests merged in 2024-09, with the labels that each got.

#662 Merging Stage into Main for release of new pricing
  app/components/AccountPlan/AccountPlan.tsx
  app/components/Sidebar/Sidebar.tsx
  app/models/portal/portal.data.ts
  app/routes/account.$accountId.settings.plan/components/FreeAccountPlan/FreeAccountPlan.tsx
  app/routes/account.$accountId.settings.plan/components/FreeAccountPlan/index.ts
  app/routes/account.$accountId.settings.plan/components/FreePlanLimitCard/FreePlanLimitCard.tsx
  app/routes/account.$accountId.settings.plan/components/FreePlanLimitCard/index.ts
  app/routes/account.$accountId.settings.plan/components/UnlimitedAccountOverviewCard/UnlimitedPlanOverviewCard.tsx
  app/routes/account.$accountId.settings.plan/components/UnlimitedAccountOverviewCard/index.ts
  app/routes/account_.$accountId.upgrade/route.tsx
  app/routes/api.stripe.webhook/route.tsx
  app/utils/notifications.server.ts
  app/utils/planUtils.ts
  app/utils/updatePlan.server.ts
  pnpm-lock.yaml
Labels: enhancement

#663 fix: set billing cycle anchor
  app/models/stripe/stripe.data.ts
  app/routes/api.stripe.checkout-session/route.tsx
Labels: bug

#664 feat: update monthly relay limit UI
  app/models/portal/queries.graphqls
  app/routes/account.$accountId.settings._index/view.tsx
  app/routes/account_.$accountId.update/components/AccountForm/AccountForm.tsx
  app/routes/account_.$accountId.update/route.tsx
Labels: enhancement

#665 chore: update readme with stripe webhook forwarding instructions
  README.md
Labels: documentation

#668 feat: enable monthly relay limit and bug fixes
  README.md
  app/models/portal/portal.data.ts
  app/models/portal/queries.graphqls
  app/routes/account.$accountId.billing/route.tsx
  app/routes/account.$accountId.settings._index/view.tsx
  app/routes/account.$accountId.settings.plan/components/FreeAccountPlan/FreeAccountPlan.tsx
  app/routes/account.$accountId.settings.plan/components/FreePlanLimitCard/FreePlanLimitCard.tsx
  app/routes/account.$accountId.settings.plan/components/FreePlanLimitCard/index.ts
  app/routes/account.$accountId.settings.plan/components/StarterAccountPlan/StarterAccountPlan.tsx
  app/routes/account.$accountId.settings.plan/components/StarterAccountPlan/index.ts
  app/routes/account.$accountId.settings.plan/components/StarterPlanLimitCard/StarterPlanLimitCard.tsx
  app/routes/account.$accountId.settings.plan/components/StarterPlanLimitCard/index.ts
  app/routes/account.$accountId.settings.plan/components/UnlimitedAccountOverviewCard/UnlimitedPlanOverviewCard.tsx
  app/routes/account.$accountId.settings.plan/route.test.tsx
  app/routes/account.$accountId.settings.plan/view.test.tsx
  app/routes/account.$accountId.settings.plan/view.tsx
  app/routes/account_.$accountId.create/route.tsx
  app/routes/account_.$accountId.update/components/AccountForm/AccountForm.tsx
  app/routes/account_.$accountId.update/route.tsx
  app/routes/api.stripe.subscription-delete/route.tsx
  app/routes/api.stripe.webhook/route.tsx
Labels: enhancement

#671 README update
  README.md
  app/routes/account_.$accountId.create/components/AccountPlansContainer/AccountPlansContainer.tsx
Labels: bug

#672 [Urgent Release] Bug fix for new app creation
  README.md
  app/routes/account_.$accountId.create/components/AccountPlansContainer/AccountPlansContainer.tsx
Labels: bug

#675 Remove refs to old plans
  .github/workflows/validate.yml
  README.md
  app/components/AccountPlan/AccountPlan.tsx
  app/models/portal/portal.data.ts
  app/models/portal/queries.graphqls
  app/routes/account.$accountId.settings.plan/components/AutoScalePlanOverviewCard/AutoScalePlanOverviewCard.tsx
  app/routes/account.$accountId.settings.plan/components/AutoScalePlanOverviewCard/index.ts
  app/routes/account.$accountId.settings.plan/route.test.tsx
  app/routes/account.$accountId.settings/view.tsx
  app/routes/account_.$accountId.create/components/AccountPlansContainer/AccountPlansContainer.tsx
  app/routes/account_.$accountId.create/route.tsx
  app/utils/planUtils.ts
Labels: enhancement

#676 fix: remove refs to old plan types
  .github/workflows/validate.yml
  README.md
  app/components/AccountPlan/AccountPlan.tsx
  app/models/portal/portal.data.ts
  app/models/portal/queries.graphqls
  app/routes/account.$accountId.settings.plan/components/AutoScalePlanOverviewCard/AutoScalePlanOverviewCard.tsx
  app/routes/account.$accountId.settings.plan/components/AutoScalePlanOverviewCard/index.ts
  app/routes/account.$accountId.settings.plan/route.test.tsx
  app/routes/account.$accountId.settings/view.tsx
  app/routes/account_.$accountId.create/components/AccountPlansContainer/AccountPlansContainer.tsx
  app/routes/account_.$accountId.create/route.tsx
  app/utils/planUtils.ts
Labels: bug
