Repository pokt-foundation/grove-portal, pull requests merged in 2025-02, with the labels that each got.

#692 Downgrading `lucide-react` to a stable version to solve failing Vercel deployments
  .vercelignore
  app/components/AccountDrawer/AccountDrawer.tsx
  app/components/AccountSelect/AccountSelect.tsx
  app/components/AppHeader/AppHeader.tsx
  app/components/ChainSelect/ChainSelect.tsx
  app/components/ChainsDropdown/ChainsDropdown.tsx
  app/components/CodeEditor/CodeEditor.tsx
  app/components/ContextMenuTarget/ContextMenuTarget.tsx
  app/components/CopyTextButton/CopyTextButton.tsx
  app/components/FluidSelect/FluidSelect.tsx
  app/components/Sidebar/Sidebar.tsx
  app/components/Sidebar/components/SidebarNavLinks.tsx
  app/hooks/useActionNotification.tsx
  app/models/portal/mutations.graphqls
  app/root.tsx
  app/routes/account.$accountId.$appId._index/components/AppEndpointsTable/AppEndpointsTable.tsx
  app/routes/account.$accountId.$appId._index/components/FavoriteChain/FavoriteChain.tsx
  app/routes/account.$accountId.$appId._index/route.tsx
  app/routes/account.$accountId.$appId.security/components/AddSettingsButton/AddSettingsButton.tsx
  app/routes/account.$accountId.$appId.security/components/ChainWhitelistTable/ChainWhitelistTable.tsx
  app/routes/account.$accountId.$appId.security/components/ChainsTable/ChainsTable.tsx
  app/routes/account.$accountId.$appId/components/ApplicationHeader/ApplicationHeader.tsx
  app/routes/account.$accountId.$appId/components/DeleteApplication/DeleteApplication.tsx
  app/routes/account.$accountId._index/components/AnnouncementAlert/AnnouncementAlert.tsx
  app/routes/account.$accountId._index/components/ChartPeriodSelector/ChartPeriodSelector.tsx
  app/routes/account.$accountId.billing.$invoiceId/components/InvoiceHeader/InvoiceHeader.tsx
  app/routes/account.$accountId.billing.$invoiceId/components/InvoiceUsageDataTable/BillingCycleUsageDataTable.tsx
  app/routes/account.$accountId.settings.members/components/TeamMemberAction/TeamMemberAction.tsx
  app/routes/account.$accountId.settings.plan/components/EnterpriseAccountOverviewCard/EnterpriseAccountOverviewCard.tsx
  app/routes/account.$accountId.settings.plan/components/UnlimitedAccountOverviewCard/UnlimitedPlanOverviewCard.tsx
  app/routes/api.auth.auth0/route.tsx
  app/routes/user.accounts/components/AccountsTable/AccountsTable.tsx
  app/routes/user.accounts/components/InvitedAccountAction/InvitedAccountAction.tsx
  app/routes/user/route.tsx
  app/utils/auth.server.ts
  cypress/tsconfig.tsbuildinfo
  package.json
  pnpm-lock.yaml
  tsconfig.tsbuildinfo
  vite.config.ts
Labels: bug

#693 Sandbox fixes, new logos
  app/utils/chainUtils.ts
  public/chain-logos/berachain-bartio-testnet.svg
  public/chain-logos/berachain.svg
  public/chain-logos/ink.svg
  public/chain-logos/linea.svg
  public/chain-logos/mantle.svg
  public/chain-logos/sei.svg
  public/chain-logos/sonic.svg
  public/chain-logos/tron.svg
  public/chain-logos/xrpl-evm-devnet.svg
Labels: bug, enhancement

#694 Merge all recent changes from `stage` to `main`
  .vercelignore
  app/components/AccountDrawer/AccountDrawer.tsx
  app/components/AccountPlan/AccountPlan.tsx
  app/components/AccountSelect/AccountSelect.tsx
  app/components/AppHeader/AppHeader.tsx
  app/components/AppHeader/NovuNotificationPopover/NovuNotificationPopover.tsx
  app/components/ChainSelect/ChainSelect.tsx
  app/components/ChainsDropdown/ChainsDropdown.tsx
  app/components/CodeEditor/CodeEditor.tsx
  app/components/ContextMenuTarget/ContextMenuTarget.tsx
  app/components/CopyTextButton/CopyTextButton.tsx
  app/components/FluidSelect/FluidSelect.tsx
  app/components/Sidebar/Sidebar.tsx
  app/components/Sidebar/components/SidebarNavLinks.tsx
  app/hooks/useActionNotification.tsx
  app/models/portal/mutations.graphqls
  app/root.tsx
  app/routes/account.$accountId.$appId._index/components/AppEndpointsTable/AppEndpointsTable.tsx
  app/routes/account.$accountId.$appId._index/components/FavoriteChain/FavoriteChain.tsx
  app/routes/account.$accountId.$appId._index/route.tsx
  app/routes/account.$accountId.$appId.security/components/AddSettingsButton/AddSettingsButton.tsx
  app/routes/account.$accountId.$appId.security/components/ChainWhitelistTable/ChainWhitelistTable.tsx
  app/routes/account.$accountId.$appId.security/components/ChainsTable/ChainsTable.tsx
  app/routes/account.$accountId.$appId.security/components/SimpleStringTable/SimpleStringTable.tsx
  app/routes/account.$accountId.$appId/components/ApplicationHeader/ApplicationHeader.tsx
  app/routes/account.$accountId.$appId/components/DeleteApplication/DeleteApplication.tsx
  app/routes/account.$accountId._index/components/AnnouncementAlert/AnnouncementAlert.tsx
  app/routes/account.$accountId._index/components/ChartPeriodSelector/ChartPeriodSelector.tsx
  app/routes/account.$accountId.billing.$invoiceId/components/InvoiceHeader/InvoiceHeader.tsx
  app/routes/account.$accountId.billing.$invoiceId/components/InvoiceUsageDataTable/BillingCycleUsageDataTable.tsx
  app/routes/account.$accountId.settings.members/components/TeamMemberAction/TeamMemberAction.tsx
  app/routes/account.$accountId.settings.plan/components/EnterpriseAccountOverviewCard/EnterpriseAccountOverviewCard.tsx
  app/routes/account.$accountId.settings.plan/components/UnlimitedAccountOverviewCard/UnlimitedPlanOverviewCard.tsx
  app/routes/api.auth.auth0/route.tsx
  app/routes/user.accounts/components/AccountsTable/AccountsTable.tsx
  app/routes/user.accounts/components/InvitedAccountAction/InvitedAccountAction.tsx
  app/routes/user/route.tsx
  app/utils/auth.server.ts
  app/utils/chainUtils.ts
  cypress/tsconfig.tsbuildinfo
  package.json
  pnpm-lock.yaml
  public/chain-logos/berachain-bartio-testnet.svg
  public/chain-logos/berachain.svg
  public/chain-logos/ink.svg
  public/chain-logos/linea.svg
  public/chain-logos/mantle.svg
  public/chain-logos/sei.svg
  public/chain-logos/sonic.svg
  public/chain-logos/tron.svg
  public/chain-logos/xrpl-evm-devnet.svg
  tsconfig.tsbuildinfo
  vite.config.ts
Labels: bug, documentation, enhancement

#695 Updated sonic and xrpl-evm-devnet
  public/chain-logos/sonic.svg
  public/chain-logos/xrpl-evm-devnet.svg
Labels: enhancement

#697 Index fix
  app/root/components/Document/Document.tsx
Labels: bug

#698 Bumping Indexing blocker to PROD
  app/root/components/Document/Document.tsx
Labels: bug

#699 Add HTTP Headers to disallow bot crawling
  app/components/CodeEditor/CodeEditor.tsx
  vercel.json
  vite.config.ts
Labels: bug
